// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/19/2026, 10:07:44 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/will/Documents/GitHub/FART/fart-vue/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/will/Documents/GitHub/FART/fart-vue/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/will/Documents/GitHub/FART/fart-vue/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/will/Documents/GitHub/FART/fart-vue/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/will/Documents/GitHub/FART/fart-vue/plugins/**/*.{js,ts,mjs}","/Users/will/Documents/GitHub/FART/fart-vue/composables/**/*.{js,ts,mjs}","/Users/will/Documents/GitHub/FART/fart-vue/stores/**/*.{js,ts,mjs}","/Users/will/Documents/GitHub/FART/fart-vue/utils/**/*.{js,ts,mjs}","/Users/will/Documents/GitHub/FART/fart-vue/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/will/Documents/GitHub/FART/fart-vue/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/will/Documents/GitHub/FART/fart-vue/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/will/Documents/GitHub/FART/fart-vue/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;