// Gcode header validation for Prusa printers

export interface GcodeMetadata {
  printerModel?: string
  nozzleDiameter?: number
  filamentType?: string
  filamentUsedG?: number
  printTime?: string
  layerHeight?: number
  generatedBy?: string
  warnings: string[]
  errors: string[]
}

// Parse gcode header comments to extract metadata
export function parseGcodeHeader(gcodeContent: Buffer | string): GcodeMetadata {
  const content = typeof gcodeContent === 'string'
    ? gcodeContent
    : gcodeContent.toString('utf-8', 0, Math.min(gcodeContent.length, 10000)) // Only read first 10KB for headers

  const metadata: GcodeMetadata = {
    warnings: [],
    errors: [],
  }

  const lines = content.split('\n').slice(0, 200) // Check first 200 lines for metadata

  for (const line of lines) {
    const trimmed = line.trim()

    // Skip non-comment lines for metadata extraction
    if (!trimmed.startsWith(';')) continue

    const comment = trimmed.substring(1).trim()

    // Printer model detection (PrusaSlicer format)
    if (comment.startsWith('printer_model =')) {
      metadata.printerModel = comment.split('=')[1]?.trim()
    }

    // Alternative format: ; printer_model = MK4
    if (comment.includes('printer_model')) {
      const match = comment.match(/printer_model\s*[=:]\s*(.+)/i)
      if (match) metadata.printerModel = match[1].trim()
    }

    // Nozzle diameter
    if (comment.includes('nozzle_diameter')) {
      const match = comment.match(/nozzle_diameter\s*[=:]\s*([\d.]+)/i)
      if (match) metadata.nozzleDiameter = parseFloat(match[1])
    }

    // Filament type
    if (comment.includes('filament_type')) {
      const match = comment.match(/filament_type\s*[=:]\s*(.+)/i)
      if (match) metadata.filamentType = match[1].trim()
    }

    // Filament used (grams)
    if (comment.includes('filament used [g]') || comment.includes('filament_used_g')) {
      const match = comment.match(/[\d.]+/)
      if (match) metadata.filamentUsedG = parseFloat(match[0])
    }

    // Estimated print time
    if (comment.includes('estimated printing time') || comment.includes('TIME:')) {
      const match = comment.match(/(\d+[hms]\s*)+/i) || comment.match(/TIME:\s*(\d+)/i)
      if (match) metadata.printTime = match[0].trim()
    }

    // Layer height
    if (comment.includes('layer_height')) {
      const match = comment.match(/layer_height\s*[=:]\s*([\d.]+)/i)
      if (match) metadata.layerHeight = parseFloat(match[1])
    }

    // Generated by (slicer info)
    if (comment.includes('generated by') || comment.includes('G-code generated')) {
      metadata.generatedBy = comment
    }
  }

  return metadata
}

// Validate gcode against a target printer
export function validateGcodeForPrinter(
  metadata: GcodeMetadata,
  targetPrinterModel: string
): GcodeMetadata {
  const result = { ...metadata }

  // Normalize printer model names
  const normalizeModel = (model: string): string => {
    return model.toLowerCase()
      .replace(/prusa/i, '')
      .replace(/\s+/g, '')
      .replace(/-/g, '')
      .trim()
  }

  // Check printer model compatibility
  if (metadata.printerModel) {
    const gcodeModel = normalizeModel(metadata.printerModel)
    const targetModel = normalizeModel(targetPrinterModel)

    // Define compatible model groups
    const mk4Models = ['mk4', 'mk4s', 'mk4is']
    const mk3Models = ['mk3', 'mk3s', 'mk3s+', 'mk3splus']
    const miniModels = ['mini', 'mini+', 'miniplus']
    const xlModels = ['xl']

    const getModelGroup = (model: string): string => {
      if (mk4Models.some(m => model.includes(m))) return 'mk4'
      if (mk3Models.some(m => model.includes(m))) return 'mk3'
      if (miniModels.some(m => model.includes(m))) return 'mini'
      if (xlModels.some(m => model.includes(m))) return 'xl'
      return model
    }

    const gcodeGroup = getModelGroup(gcodeModel)
    const targetGroup = getModelGroup(targetModel)

    if (gcodeGroup !== targetGroup) {
      result.errors.push(
        `Printer mismatch: This gcode was generated for "${metadata.printerModel}" but you're trying to print on "${targetPrinterModel}". This may cause print failures or damage.`
      )
    }
  } else {
    result.warnings.push('Could not detect printer model from gcode. Make sure this file is compatible with your printer.')
  }

  // Check nozzle diameter (most Prusas use 0.4mm)
  if (metadata.nozzleDiameter && metadata.nozzleDiameter !== 0.4) {
    result.warnings.push(
      `Non-standard nozzle size: This gcode was sliced for a ${metadata.nozzleDiameter}mm nozzle. Make sure your printer has the correct nozzle installed.`
    )
  }

  // Check filament type warnings
  if (metadata.filamentType) {
    const filament = metadata.filamentType.toUpperCase()
    if (filament.includes('ABS') || filament.includes('ASA')) {
      result.warnings.push(
        `High-temperature filament detected (${metadata.filamentType}). Ensure you have proper ventilation and an enclosure if needed.`
      )
    }
    if (filament.includes('FLEX') || filament.includes('TPU')) {
      result.warnings.push(
        `Flexible filament detected (${metadata.filamentType}). Ensure your extruder is configured for flexible materials.`
      )
    }
  }

  return result
}

// Main validation function
export function validateGcode(
  gcodeContent: Buffer | string,
  targetPrinterModel: string
): GcodeMetadata {
  console.log(`[DEBUG] validateGcode: Starting validation for printer "${targetPrinterModel}"`)

  const metadata = parseGcodeHeader(gcodeContent)
  console.log(`[DEBUG] validateGcode: Parsed metadata:`, JSON.stringify(metadata, null, 2))

  const validated = validateGcodeForPrinter(metadata, targetPrinterModel)
  console.log(`[DEBUG] validateGcode: Validation result - ${validated.errors.length} errors, ${validated.warnings.length} warnings`)

  return validated
}
